# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Blog de l'equipe Printemps

description: Blog de l'equipe Printemps

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
authors_path: authors.html
